language: cpp
compiler:
  - gcc
  - clang
before_script:
  - ./configure --enable-version=18
branches:
  only:
    - master
    - compiler
notifications:
  recipients:
    - nkhuyu@gmail.com
  email:
    on_success: change
    on_failure: always

