#!/bin/bash

# pass in file name
file_name=$1 

# Text color variables
txtund=$(tput sgr 0 1)          # Underline
txtbld=$(tput bold)             # Bold
bldred=${txtbld}$(tput setaf 1) #  red
bldblu=${txtbld}$(tput setaf 4) #  blue
bldwht=${txtbld}$(tput setaf 7) #  white
txtrst=$(tput sgr0)             # Reset
info=${bldwht}*${txtrst}        # Feedback
pass=${bldblu}*${txtrst}
warn=${bldred}*${txtrst}
ques=${bldblu}?${txtrst}

# date
now=$(date)
echo "======$now console output:"
/usr/bin/g++ -Wall -o output_file $file_name

if [ $?==0 ]; then
    echo "=====build successful====="
    echo "$now output:"
    ./output_file
else
    echo "=====Failed#####====="
fi
